# Generated by Django 3.2.25 on 2025-10-09 07:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPracticePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('case_title', models.CharField(max_length=255, verbose_name='Название дела')),
                ('case_type', models.CharField(blank=True, help_text='Например: Гражданское дело, Уголовное дело и т.д.', max_length=100, verbose_name='Тип дела')),
                ('case_description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание дела')),
                ('challenge', wagtail.fields.RichTextField(blank=True, help_text='С какой проблемой обратился клиент', verbose_name='Проблема/Задача')),
                ('solution', wagtail.fields.RichTextField(blank=True, help_text='Как была решена проблема', verbose_name='Решение/Результат')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала дела')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения дела')),
                ('status', models.CharField(blank=True, help_text='Например: Выиграно, Урегулировано, В процессе и т.д.', max_length=100, verbose_name='Статус дела')),
                ('court', models.CharField(blank=True, max_length=255, verbose_name='Суд/Орган')),
                ('gallery_images', wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(icon='image', verbose_name='Изображение'))], blank=True, use_json_field=True, verbose_name='Галерея изображений')),
            ],
            options={
                'verbose_name': 'Юридическая практика',
                'verbose_name_plural': 'Юридическая практика',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PracticeGalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание галереи')),
            ],
            options={
                'verbose_name': 'Галерея практики',
                'verbose_name_plural': 'Галереи практики',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('client_initials', models.CharField(blank=True, max_length=10, verbose_name='Инициалы')),
                ('review_title', models.CharField(max_length=255, verbose_name='Заголовок отзыва')),
                ('review_text', wagtail.fields.RichTextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=5, verbose_name='Оценка')),
                ('case_type_review', models.CharField(blank=True, max_length=100, verbose_name='Тип дела')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('review_date', models.DateField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='home.legalpracticepage', verbose_name='Страница практики')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['-review_date'],
            },
        ),
    ]
