# Generated by Django 4.1.13 on 2025-09-21 18:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', verbose_name='Заголовок')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', verbose_name='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', verbose_name='Картинка'))], blank=True, use_json_field=True),
        ),
    ]
