# Generated by Django 3.2.25 on 2025-10-09 12:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0001_initial'),
        ('home', '0002_clientreview_legalpracticepage_practicegallerypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание страницы контактов')),
            ],
            options={
                'verbose_name': 'Страница контактов',
                'verbose_name_plural': 'Страница контактов',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание страницы политики')),
            ],
            options={
                'verbose_name': 'Страница политики',
                'verbose_name_plural': 'Страница политики',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PricePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание страницы цен')),
            ],
            options={
                'verbose_name': 'Страница цен',
                'verbose_name_plural': 'Страница цен',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UslugiPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание страницы услуг')),
            ],
            options={
                'verbose_name': 'Страница услуг',
                'verbose_name_plural': 'Страница услуг',
            },
            bases=('wagtailcore.page',),
        ),
    ]
