# Generated by Django 3.2.25 on 2025-10-07 12:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0078_referenceindex'),
        ('home', '0003_homepage_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница', 'verbose_name_plural': 'Главные страницы'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='city',
            field=models.CharField(blank=True, default='Симферополь', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание услуг'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=models.EmailField(default='mail@crimea-yurist.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фон картинки'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, default='Юрист по Крыму', max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='map_url',
            field=models.URLField(blank=True, default='https://yandex.ru/map-widget/v1/?ll=34.097897%2C44.954033&mode=search&oid=245071578035&ol=biz&z=16.64', verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=models.CharField(default='+7 978 910-42-97', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='region',
            field=models.CharField(default='Республика Крым', max_length=100, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Улица, дом'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', verbose_name='Заголовок')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', verbose_name='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', verbose_name='Картинка'))], blank=True, use_json_field=True, verbose_name='Контент'),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=10, null=True, verbose_name='Стоимость')),
                ('price_description', models.CharField(blank=True, default='от', help_text='Например: от, договорная, бесплатная консультация', max_length=100, verbose_name='Описание цены')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='Улица, дом')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('region', models.CharField(default='Республика Крым', max_length=100, verbose_name='Регион')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(default='+7 978 910-42-97', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='mail@crimea-yurist.ru', max_length=254, verbose_name='Email')),
                ('map_url', models.URLField(blank=True, default='https://yandex.ru/map-widget/v1/?ll=34.097897%2C44.954033&mode=search&oid=245071578035&ol=biz&z=16.64', verbose_name='Ссылка на карту')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Описание услуги')),
                ('content', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', verbose_name='Заголовок')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', verbose_name='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', verbose_name='Картинка'))], blank=True, use_json_field=True, verbose_name='Дополнительный контент')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Страница услуги',
                'verbose_name_plural': 'Страницы услуг',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('city_name', models.CharField(help_text='Например: Юрист Симферополь', max_length=100, verbose_name='Название услуги по городу')),
                ('hero_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('street_address', models.CharField(blank=True, max_length=255, verbose_name='Улица, дом')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('region', models.CharField(default='Республика Крым', max_length=100, verbose_name='Регион')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('phone', models.CharField(default='+7 978 910-42-97', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='mail@crimea-yurist.ru', max_length=254, verbose_name='Email')),
                ('map_url', models.URLField(blank=True, default='https://yandex.ru/map-widget/v1/?ll=34.097897%2C44.954033&mode=search&oid=245071578035&ol=biz&z=16.64', verbose_name='Ссылка на карту')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='УТП описание услуг в городе')),
                ('content', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', verbose_name='Заголовок')), ('paragraph', wagtail.blocks.RichTextBlock(icon='pilcrow', verbose_name='Текст')), ('image', wagtail.images.blocks.ImageChooserBlock(icon='image', verbose_name='Картинка'))], blank=True, use_json_field=True, verbose_name='Подробное описание')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фон картинки')),
            ],
            options={
                'verbose_name': 'Страница города',
                'verbose_name_plural': 'Страницы городов',
            },
            bases=('wagtailcore.page',),
        ),
    ]
